### ISSUE TITLE
php-re2 slower than pcre?

### ISSUE THREAD

**Issue by tsuna** [arraypad/php-re2#3]
Hi,
thank you very much for writing a PHP extension to wrap RE2.  StumbleUpon is very interested in using it.

I compiled RE2 from their last version (changeset 63:7007b2180a42 in their hg repo).  I compiled RE2 with `-DPIC -fpic -Wall -O3 -g` and php-re2 (revision arraypad/php-re2@ff5533a1) with `-DPIC -fPIC -fpic -DNDEBUG -O2 -g`.

``` php
<?php

function test($url) {
  $pcre = microtime(true);
  for ($i = 0; $i < 1000; $i++) {
    preg_match('@(\d{4})([-/]?)([0-1]?\d{1})([-/]?)(\d{1,2})@', $url);
  }
  $pcre = (microtime(true) - $pcre) * 1000;
  $re2 = microtime(true);
  for ($i = 0; $i < 1000; $i++) {
    re2_match('(\d{4})([-/]?)([0-1]?\d{1})([-/]?)(\d{1,2})', $url);
  }
  $re2 = (microtime(true) - $re2) * 1000;
  printf("%.2fms vs %.2fms %s\n", $pcre, $re2, $url);
}

test('http://www.example.com/1234-01-12');
```

This prints:  `3.10ms vs 34.99ms http://www.example.com/1234-01-12`

This doesn't look right to me.  How come it's 10x slower?  Am I doing something stupid?  Have you benchmarked the extension?  If yes, what speedup do you typically see?

Also I noticed that php-re2 doesn't support having the delimiters in the regexp.

``` php
<?php
print_r(re2_match('/f(o)o/', 'omg foo bar', $match));  // Doesn't work, returns 0
print_r(re2_match('f(o)o', 'omg foo bar', $match));    // Works, returns 1
```

PS: This is on a test server with:

```
$ uname -r
2.6.32-31-server
$ php -v
PHP 5.3.6-11~lucid+5 with Suhosin-Patch (cli) (built: May 16 2011 16:39:09) 
Copyright (c) 1997-2011 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2011 Zend Technologies
```

Server is a dual-L5630 with 48GB of RAM.

**Comment by arraypad** [comment]
Hi, glad to hear you're considering it :)

If you're using the same pattern lots, like in your benchmark, performance is vastly improved by compiling the pattern first. For example:

```
$p = new Re2('(\d{4})([-/]?)([0-1]?\d{1})([-/]?)(\d{1,2})');
for ($i = 0; $i < 1000; $i++) {
  re2_match($p, $url);
}
```

With your example I get similar results (5.10ms vs 22.81ms). Having moved the compilation out of the loop as above, I get 5.22ms vs 1.19ms. Using the equivalent feature of PCRE (the S modifier) makes them more comparable but re2 is still slightly faster (2.55ms vs 1.19ms). The gap widens with more iterations, for 10,000 it's 20.45ms vs 6.20ms.

As for delimiters, I wasn't intending to support them since pattern options can be set with an Re2Options object. I appreciate that it's a gotcha coming from PCRE though, I'll look into it soon.

**Comment by tsuna** [comment]
OK, yeah, when compiling the RE outside of the loop I now get `34.34ms vs 6.04ms`.  Sounds like the process of building the automaton in RE2 isn't very cheap.  I confirmed the timings by writing the same code in C++ and I get similar differences when creating a new `RE2` object each time vs compiling it once.

``` c++

#include <cassert>
#include <cstdio>
#include <ctime>
#include "re2/re2.h"

uint64_t nanoTime() {
  struct timespec ts;
  clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
  return ((uint64_t) ts.tv_sec) * 1000000000UL
    + ((uint64_t) ts.tv_nsec);
}

#define ITER 1000

int main () {
  const char regexp[] = "(\\d{4})([-/]?)([0-1]?\\d{1})([-/]?)(\\d{1,2})";
  const char subject[] = "http://www.example.com/1234-01-12";
  uint64_t start, stop;

  start = nanoTime();
  {
    RE2 *re;
    for (int i = 0; i < ITER; i++) {
      re2::StringPiece subject_piece(subject);
      re = new RE2(regexp);
      assert(re->ok());
      re->Match(subject_piece, 0, subject_piece.size(), RE2::UNANCHORED, NULL, 0);
      delete re;
    }
  }
  stop = nanoTime();
  printf("new RE2 each time: %5.2fms\n", (stop - start) / (double) 1000000.0);

  start = nanoTime();
  {
    for (int i = 0; i < ITER; i++) {
      re2::StringPiece subject_piece(subject);
      RE2::PartialMatch(subject_piece, regexp);
    }
  }
  stop = nanoTime();
  printf("RE2::PartialMatch: %5.2fms\n", (stop - start) / (double) 1000000.0);

  start = nanoTime();
  {
    RE2 *re = new RE2(regexp);
    for (int i = 0; i < ITER; i++) {
      re2::StringPiece subject_piece(subject);
      assert(re->ok());
      re->Match(subject_piece, 0, subject_piece.size(), RE2::UNANCHORED, NULL, 0);
    }
    delete re;
  }
  stop = nanoTime();
  printf("pre-compiled RE2:  %5.2fms\n", (stop - start) / (double) 1000000.0);

  return 0;
}
```

This prints (on the same machine):

```
new RE2 each time: 33.81ms
RE2::PartialMatch: 33.70ms
pre-compiled RE2:   0.32ms
```

Seems like the README should be adjusted to spell out clearly that people upgrading to RE2 in order to speed up their regexp matching code absolutely must compile the regexp and re-use the compiled form.  It's easy to overlook, as people might get excited about RE2 and simply replace `preg_` with `re2_` in their code (like I did).

So this is a non-issue after all.  Once again, thank you for writing this extension.

PS: Yes in the code above I know that I'm creating a new `StringPiece` every time and calling `ok()` unnecessarily, but I wanted to mimic what the PHP extension does.
