### ISSUE TITLE
PHP 5.5 Support

### ISSUE THREAD

**Issue by robertodecurnex** [arraypad/php-re2#7]
```
11 PASSED TESTS
0 SKIPPED TESTS
4 FAILED TESTS:
./php-re2/tests/class.phpt
./php-re2/tests/null.phpt
./php-re2/tests/options.phpt
./php-re2/tests/split.phpt
```

Its returning just the first match group on each test.

`options.phpt` example

Expectation:

```
array(2) {
  [0]=>
  string(2) "aa"
  [1]=>
  string(2) "aa"
}
```

Output:

```
array(1) {
  [0]=>
  string(2) "aa"
}
```

**Comment by robertodecurnex** [comment]
It also works case insensitive, regardless of the given options.

<pre>
#!/usr/bin/php
<?
$regex = '[a-z]';
$regexObject = new Re2($regex);
var_dump($regexObject->getOptions()->getCaseSensitive());
var_dump($regexObject->getPattern());
re2_match(
  $regexObject,
  'a',
  $matches
);
var_dump($matches);
re2_match(
  $regex,
  'a',
  $matches2
);
var_dump($matches2);
  
re2_match(
  $regexObject,
  'A',
  $matches3
);
var_dump($matches3);
re2_match(
  $regex,
  'A',
  $matches4
);
var_dump($matches4);
</pre>

<pre>
bool(true)
string(5) "[a-z]"
array(1) {
  [0]=>
  string(1) "a"
}
array(1) {
  [0]=>
  string(1) "a"
}
array(1) {
  [0]=>
  string(1) "A"
}
NULL
</pre>

**Comment by JalfResi** [comment]
Any movement on this issue? It's quite the showstopper!
